# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xt58vBty2Go-_OiSNhGVIunHN36oSGjs
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
import pickle

# Load data
df = pd.read_csv("Customers(in).csv")

# Encode gender (Female/Male → 0/1)
le = LabelEncoder()
df["gender"] = le.fit_transform(df["gender"])

# Features & target
X = df.drop(["customer_id", "churn"], axis=1)
y = df["churn"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Save model
with open("churn_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("✅ Model trained and saved as churn_model.pkl")

pwd





























